version: '3'

services:

  orchestrator:
    build:
      context: .
      dockerfile: ./Orchestrator/Dockerfile
    ports:
      - "8080:8080"
    container_name: orchesterator
    networks:
      - orchesterator
  agent:
    build:
      context: .
      dockerfile: ./Agent/Dockerfile
    deploy:
      replicas: 3
    networks:
      - orchesterator
  db:
    image: adminsemy/yandex_calculator_postrgrees
    container_name: db_orchesterator
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - orchesterator


networks:
  orchesterator:

volumes:
  db_data:
